version: '3'
tasks:
  doc:
    desc: Generate documentation and inject into README.md after special tags
    cmds:
      - terraform-docs markdown table . --output-file README.md --output-mode inject
  fmt:
    desc: Run terraform fmt
    cmds:
      - tofu fmt
