#cloud-config
hostname: ${hostname}
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - software-properties-common
  - tmux
  - mc
  - htop
  - qemu-guest-agent

users:
  - name: root
    ssh_authorized_keys:
      - "${ssh_public_key}"
    shell: /bin/bash
    lock_passwd: false
    passwd: "*"
    sudo: ALL=(ALL) NOPASSWD:ALL


write_files:
  - path: /root/init.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -eux

      # Add Docker GPG key
      mkdir -p /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

      # Add Docker repo
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable" > /etc/apt/sources.list.d/docker.list

      apt-get update -y
      apt-get install -y docker-ce docker-ce-cli containerd.io
      systemctl enable --now docker

      wget https://raw.githubusercontent.com/dokku/dokku/v${dokku_version}/bootstrap.sh
      DOKKU_TAG=v${dokku_version} bash bootstrap.sh
      cat ~/.ssh/authorized_keys | dokku ssh-keys:add admin

runcmd:
  - systemctl start qemu-guest-agent
  - systemctl enable qemu-guest-agent
  - (/root/init.sh && touch /root/.bootstrap-done || /root/.bootstrap-failed) > /var/log/init.log 2>&1
